create table latertube_videos (
    video_id INTEGER primary key generated by default as identity,
    video_title TEXT not null,
    video_thumbnail_url TEXT not null,
    video_url TEXT not null,
    video_description TEXT,
    video_rating INTEGER default 1 not null,
    genre_id INTEGER references latertube_genres(genre_id) on delete cascade,
    video_created_time TIMESTAMPTZ default now() not null
);
